#include "expression_def.hpp"
#include "config.hpp"

namespace cpp{ namespace parser{
	BOOST_SPIRIT_INSTANTIATE(expression_type,iterator_type,context_type)
	BOOST_SPIRIT_INSTANTIATE(variable_declaration_type,iterator_type,context_type)
	BOOST_SPIRIT_INSTANTIATE(function_declarator_type,iterator_type,context_type)
	BOOST_SPIRIT_INSTANTIATE(declarator_initializer_type,iterator_type,context_type)
	
	BOOST_SPIRIT_INSTANTIATE(expression_type,iterator_file_type,context_file_type)
	BOOST_SPIRIT_INSTANTIATE(variable_declaration_type,iterator_file_type,context_file_type)
	BOOST_SPIRIT_INSTANTIATE(function_declarator_type,iterator_file_type,context_file_type)
	BOOST_SPIRIT_INSTANTIATE(declarator_initializer_type,iterator_file_type,context_file_type)
}}